In [1]:
import numpy as np

In [21]:
# Creating a matrix

A = np.array([[1,2], [3,4]]) 
print(A)

#Creating a vector

B = np.array([5,6])
print(B)

[[1 2]
 [3 4]]
[5 6]


In [7]:
# 1st column of A

print(A[:,0])

# 1st row of A

print(A[0,:])

[1 3]
[1 2]


In [10]:
# Matrix Multiplicaton -- Vector & Vector Product
# @ is used for multiplying matrices

C = np.array([25,100])
Z = B @ C

print(Z)

725


In [14]:
# Matrix Multiplicaton -- Matrix & Vector Product
# @ is used for multiplying matrices
# Matrix multiplication is associative, distributive but non-commutative

C = np.array([25,100])
Z = A @ C

print(Z)

[225 475]


In [17]:
# Creating a 5X5 identity matrix
# All diagonal elements are 1 and the others are 0

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# Creating a diagonal matrix
# All the elements are 0 except those in the diagonal

D = np.diag([1,2,3,4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
# Transposing a matrix

A_t = A.T

print(A_t)

[[1 3]
 [2 4]]


In [20]:
# Finding the trace of the matrix
# Trace of the matrix is the sum of all the diagonal elements of the matrix

print(np.trace(A))

5


In [27]:
# Calculating norms of the vectors

# l1 norm: The sum of the absolute values of the elements of a vector
print("L1 Norm:", np.linalg.norm(B, 1))

#l2 norm: Sum of the square root of the sum of all elements of a vector
print("l2 Norm:", np.linalg.norm(B, 2))

#l∞ norm: The maximum element of a vector independent of its positive or negative nature

L1 Norm: 11.0
l2 Norm: 7.810249675906654


In [29]:
# Finding the inverse of the matrix

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
# This will result in an identity matrix

print(A @ A_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [35]:
# Finding the quadratic form of an equation
# Quadratic form: x is a vector, A is a matrix then quadratic form is the product of the trasnpose of x, x and A

x = np.array([5, 6])
qf = x.T @ A @ x
print(qf)

319


In [37]:
# Gradient of a function

grad = (A + A.T) @ x
print(grad)

[40 73]
